// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
};

/* Types */
/**
 *  The error every command returns (CLAUDE.md §5, "No silent failures").
 * 
 *  Serialised as `{ code, detail }`. The UI maps `code` to a message under `errors` in
 *  `apps/desktop/src/i18n/locales/zh-CN.json`; `tsc` fails if a code has no message.
 *  `detail` is for logs and bug reports, never shown to users on its own.
 */
export type AppError = 
/**  The data directory could not be determined or is invalid. */
{ code: "DataDirUnavailable"; detail: string };

/**  Versions and the data directory, for the placeholder screen and for bug reports. */
export type AppInfo = {
	appVersion: string,
	coreVersion: string,
	dataDir: string,
};

/* Tauri Specta runtime */
export type TransportError = { code: "Transport"; detail: string };

async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E | TransportError }> {
    try {
        return { status: "ok", data: await result };
    } catch (e: unknown) {
        const code = typeof e === "object" && e !== null ? (e as { code?: unknown }).code : undefined;
        if (typeof code === "string") return { status: "error", error: e as E };
        return { status: "error", error: { code: "Transport", detail: e instanceof Error ? e.message : String(e) } };
    }
}

const _assertTypedErrorFollowsContract: <T, E>(result: Promise<T>) => Promise<any> = typedError;

