// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, AppError>(__TAURI_INVOKE("app_info")),
	/**
	 *  Tells the shell where the title bar's maximize button is, so the snap layouts overlay covers
	 *  it. Synchronous on purpose: Tauri runs synchronous commands on the UI thread, which owns the
	 *  windows.
	 */
	setMaximizeButtonBounds: (bounds: {
	right: number,
	top: number,
	width: number,
	height: number,
} | null) => typedError<null, AppError>(__TAURI_INVOKE("set_maximize_button_bounds", { bounds })),
};

/** Events */
export const events = {
	maximizeButtonChanged: makeEvent<MaximizeButtonChanged>("maximize-button-changed"),
};

/* Types */
/**
 *  The error every command returns (CLAUDE.md §5, "No silent failures").
 * 
 *  Serialised as `{ code, detail }`. The UI maps `code` to a message under `errors` in
 *  `apps/desktop/src/i18n/locales/zh-CN.json`; `tsc` fails if a code has no message.
 *  `detail` is for logs and bug reports, never shown to users on its own.
 */
export type AppError = 
/**  The data directory could not be determined or is invalid. */
{ code: "DataDirUnavailable"; detail: string } | 
/**  The UI sent a value the shell rejects. */
{ code: "InvalidArgument"; detail: string } | 
/**  A window operation failed. */
{ code: "Window"; detail: string };

/**  Versions and the data directory, for the placeholder screen and for bug reports. */
export type AppInfo = {
	appVersion: string,
	coreVersion: string,
	dataDir: string,
};

/**
 *  Where the HTML maximize button is, in whole CSS pixels. `right` is the distance from the
 *  window's right edge to the button's right edge. Caption buttons are anchored to the right, so
 *  the overlay can follow window resizes without asking the page again.
 */
export type ButtonBounds = {
	right: number,
	top: number,
	width: number,
	height: number,
};

/**
 *  Hover and press state of the maximize button. The overlay receives the mouse over the button,
 *  so the page gets no `:hover` or pointer events there and styles the button from this event.
 */
export type MaximizeButtonChanged = {
	hovered: boolean,
	pressed: boolean,
};

/* Tauri Specta runtime */
export type TransportError = { code: "Transport"; detail: string };

async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E | TransportError }> {
    try {
        return { status: "ok", data: await result };
    } catch (e: unknown) {
        const code = typeof e === "object" && e !== null ? (e as { code?: unknown }).code : undefined;
        if (typeof code === "string") return { status: "error", error: e as E };
        return { status: "error", error: { code: "Transport", detail: e instanceof Error ? e.message : String(e) } };
    }
}

const _assertTypedErrorFollowsContract: <T, E>(result: Promise<T>) => Promise<any> = typedError;

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

