use std::fs;
use std::io::Read;

use folio_core::catalog::{EntryId, EntryRecord};
use folio_core::meta::FileClass;
use folio_core::paths::RelPath;

use super::*;

pub(crate) fn entry(path: &str, kind: EntryKind) -> Entry {
    Entry {
        id: EntryId(1),
        added_ns: 0,
        record: EntryRecord {
            path: RelPath::parse(path).unwrap(),
            kind,
            class: FileClass::Other,
            size: 0,
            mtime_ns: None,
            file_id: None,
            hash: None,
        },
    }
}

/// Marks a test's own file offline, as Windows marks files in offline storage, or local again.
pub(crate) fn set_offline(path: &Path, offline: bool) {
    use std::os::windows::ffi::OsStrExt;
    use windows_sys::Win32::Storage::FileSystem::{FILE_ATTRIBUTE_NORMAL, SetFileAttributesW};
    let wide: Vec<_> = path.as_os_str().encode_wide().chain([0]).collect();
    let attributes = if offline {
        FILE_ATTRIBUTE_OFFLINE
    } else {
        FILE_ATTRIBUTE_NORMAL
    };
    // SAFETY: a live NUL-terminated path to the test's own disposable file.
    let changed = unsafe { SetFileAttributesW(wide.as_ptr(), attributes) };
    assert_ne!(changed, 0, "{}", io::Error::last_os_error());
}

#[test]
fn checked_handles_read_only_files_and_hold_paths_and_bytes_against_replacement() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().canonicalize().unwrap();
    fs::create_dir(root.join("notes")).unwrap();
    fs::write(root.join("notes/lesson.txt"), b"private lesson").unwrap();
    let pinned = PinnedEntry::resolve(&root, &entry("notes/lesson.txt", EntryKind::File)).unwrap();
    let mut file = pinned.read().unwrap();
    let mut bytes = Vec::new();
    file.read_to_end(&mut bytes).unwrap();
    assert_eq!(bytes, b"private lesson");
    assert!(matches!(
        fs::write(&pinned.path, b"replacement").map_err(io_error),
        Err(AppError::InUse(_))
    ));
    assert!(fs::rename(root.join("notes"), root.join("moved")).is_err());
    drop(file);
    drop(pinned);
    fs::rename(root.join("notes"), root.join("moved")).unwrap();
    assert!(matches!(
        PinnedEntry::resolve(&root, &entry("notes/lesson.txt", EntryKind::File)),
        Err(AppError::NotFound(_))
    ));
    let folder = PinnedEntry::resolve(&root, &entry("moved", EntryKind::Folder)).unwrap();
    assert!(matches!(folder.read(), Err(AppError::NotFound(_))));
    assert!(matches!(
        PinnedEntry::resolve(&root, &entry("moved", EntryKind::File)),
        Err(AppError::NotFound(_))
    ));
    fs::create_dir(root.join(".folio")).unwrap();
    fs::write(root.join(".folio/secret"), b"not served").unwrap();
    assert!(matches!(
        PinnedEntry::resolve(&root, &entry(".folio/secret", EntryKind::File)),
        Err(AppError::NotFound(_))
    ));
}

#[test]
fn pinned_folders_keep_renames_inside_them_working() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().canonicalize().unwrap();
    fs::create_dir(root.join("course")).unwrap();
    fs::write(root.join("course/lesson.txt"), b"lesson").unwrap();
    fs::write(root.join("course/draft.tmp"), b"saved").unwrap();
    fs::write(root.join("other.txt"), b"other").unwrap();
    let pinned = PinnedEntry::resolve(&root, &entry("course/lesson.txt", EntryKind::File)).unwrap();
    // Editors save through a temporary file renamed over the original; other programs rename
    // in the library root and its ancestors while Folio serves a file.
    fs::rename(root.join("course/draft.tmp"), root.join("course/notes.txt")).unwrap();
    fs::rename(root.join("other.txt"), root.join("renamed.txt")).unwrap();
    assert!(matches!(
        fs::rename(root.join("course"), root.join("moved")).map_err(io_error),
        Err(AppError::InUse(_))
    ));
    drop(pinned);
}

#[test]
fn links_and_junctions_cannot_redirect_catalogued_paths_outside_the_library() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("library");
    let outside = temp.path().join("outside");
    fs::create_dir(&root).unwrap();
    fs::create_dir(&outside).unwrap();
    fs::write(outside.join("secret.txt"), b"outside secret").unwrap();
    // A junction needs no symlink privilege on Windows. Both paths are disposable and
    // generated by tempfile; this creates a link and performs no shell deletion.
    let result = std::process::Command::new("cmd.exe")
        .args(["/d", "/c", "mklink", "/J"])
        .arg(root.join("jump"))
        .arg(&outside)
        .output()
        .unwrap();
    assert!(
        result.status.success(),
        "{}",
        String::from_utf8_lossy(&result.stderr)
    );
    let canonical = root.canonicalize().unwrap();
    assert!(matches!(
        PinnedEntry::resolve(&canonical, &entry("jump/secret.txt", EntryKind::File)),
        Err(AppError::NotFound(_))
    ));
    // The library root itself must also keep its canonical identity.
    assert!(matches!(
        PinnedEntry::resolve(&root.join("jump"), &entry("secret.txt", EntryKind::File)),
        Err(AppError::NotFound(_))
    ));
    assert_eq!(
        fs::read(outside.join("secret.txt")).unwrap(),
        b"outside secret"
    );
}

#[test]
fn native_actions_recheck_attribute_only_redirection_of_an_empty_folder() {
    use std::os::windows::ffi::OsStrExt;
    use windows_sys::Win32::Storage::FileSystem::FILE_WRITE_ATTRIBUTES;
    use windows_sys::Win32::System::IO::DeviceIoControl;
    use windows_sys::Win32::System::Ioctl::FSCTL_SET_REPARSE_POINT;

    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().join("library");
    let outside = temp.path().join("outside");
    fs::create_dir(&root).unwrap();
    fs::create_dir(&outside).unwrap();
    fs::write(outside.join("secret.txt"), b"untouched").unwrap();
    fs::create_dir(root.join("empty")).unwrap();
    let root = root.canonicalize().unwrap();
    let pinned = PinnedEntry::resolve(&root, &entry("empty", EntryKind::Folder)).unwrap();
    let before = pinned.identity;
    let writer = OpenOptions::new()
        .access_mode(FILE_WRITE_ATTRIBUTES)
        .share_mode(FILE_SHARE_READ | FILE_SHARE_WRITE)
        .custom_flags(FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OPEN_REPARSE_POINT)
        .open(&pinned.path)
        .unwrap();
    // Build the mount-point ABI buffer for our disposable directory and target only.
    let print: Vec<_> = outside.as_os_str().encode_wide().collect();
    let mut substitute = OsString::from(r"\??\");
    substitute.push(&outside);
    let substitute: Vec<_> = substitute.encode_wide().collect();
    let length = 8 + 2 * (substitute.len() + print.len() + 2);
    let mut buffer = 0xA000_0003_u32.to_le_bytes().to_vec();
    for value in [
        length as u16,
        0,
        0,
        (substitute.len() * 2) as u16,
        ((substitute.len() + 1) * 2) as u16,
        (print.len() * 2) as u16,
    ] {
        buffer.extend(value.to_le_bytes());
    }
    for value in substitute
        .iter()
        .copied()
        .chain([0])
        .chain(print)
        .chain([0])
    {
        buffer.extend(value.to_le_bytes());
    }
    let mut returned = 0;
    // SAFETY: synchronous call with a live owned handle, a correctly sized mount-point
    // buffer and writable byte count; no pointer outlives the call or leaves our temp paths.
    assert_ne!(
        unsafe {
            DeviceIoControl(
                writer.as_raw_handle(),
                FSCTL_SET_REPARSE_POINT,
                buffer.as_ptr().cast(),
                buffer.len() as u32,
                std::ptr::null_mut(),
                0,
                &mut returned,
                std::ptr::null_mut(),
            )
        },
        0,
        "{}",
        io::Error::last_os_error()
    );
    drop(writer);
    assert_eq!(identity(&pinned.leaf).unwrap(), before);
    assert!(matches!(pinned.validate(), Err(AppError::NotFound(_))));
    assert!(matches!(pinned.freeze(), Err(AppError::NotFound(_))));
    let junction = pinned.path.clone();
    drop(pinned);
    // Remove only the owned junction itself, never recurse through its target.
    fs::remove_dir(junction).unwrap();
    assert_eq!(fs::read(outside.join("secret.txt")).unwrap(), b"untouched");
}

#[test]
fn replacing_a_metadata_only_leaf_cannot_change_the_object_read_or_opened() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().canonicalize().unwrap();
    let path = root.join("lesson.txt");
    fs::write(&path, b"original").unwrap();
    let pinned = PinnedEntry::resolve(&root, &entry("lesson.txt", EntryKind::File)).unwrap();
    match fs::rename(&path, root.join("old.txt")) {
        Ok(()) => {
            fs::write(&path, b"replacement").unwrap();
            assert!(matches!(pinned.read(), Err(AppError::NotFound(_))));
            assert!(matches!(pinned.freeze(), Err(AppError::NotFound(_))));
        }
        Err(error) => {
            assert!(matches!(io_error(error), AppError::InUse(_)));
            let mut bytes = Vec::new();
            pinned.read().unwrap().read_to_end(&mut bytes).unwrap();
            assert_eq!(bytes, b"original");
        }
    }
}

#[test]
fn offline_attributes_are_checked_before_any_content_access() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path().canonicalize().unwrap();
    let path = root.join("offline.txt");
    fs::write(&path, b"kept offline").unwrap();
    set_offline(&path, true);
    let pinned = PinnedEntry::resolve(&root, &entry("offline.txt", EntryKind::File)).unwrap();
    assert!(!pinned.local().unwrap());
    assert!(matches!(pinned.read(), Err(AppError::NotLocal(_))));
    let frozen = pinned.freeze().unwrap();
    assert!(fs::rename(&path, root.join("moved.txt")).is_err());
    assert!(fs::write(&path, b"changed").is_err());
    drop(frozen);
    drop(pinned);
    set_offline(&path, false);
    assert_eq!(fs::read(path).unwrap(), b"kept offline");
}
